motorboat_dir = 'D:\RoyStudies\Recordings\hear-my-ship\V1\Motor Boats';
wav_files = dir(fullfile(motorboat_dir, '*.wav'));

num_files = min(5, length(wav_files));
results = cell(num_files, 1);

for i = 1:num_files
    wav_path = fullfile(motorboat_dir, wav_files(i).name);
    [data, fs] = audioread(wav_path);
    
    if size(data, 2) > 1
        data = data(:, 1);
    end
    
    v = data;
    v_tilde = abs(hilbert(v));
    v_abs = abs(v);
    
    [~, t_hat] = max(v_abs);
    diff_v = abs(v_abs - v_tilde);
    
    if t_hat < length(v_abs)
        [~, l1_offset] = min(diff_v(t_hat+1:end));
        l1 = t_hat + l1_offset;
    else
        l1 = t_hat;
    end
    
    if t_hat > 1
        [~, l2] = min(diff_v(1:t_hat-1));
    else
        l2 = t_hat;
    end
    
    time_vec = (0:length(v)-1) / fs;
    duration = time_vec(l1) - time_vec(l2);
    
    % To keep HTML size manageable, we extract a window of +/- 2 seconds around the peak
    % and decimate by a factor to reduce points.
    window_sec = 2.0;
    idx_min = max(1, t_hat - round(window_sec * fs));
    idx_max = min(length(v), t_hat + round(window_sec * fs));
    
    decimation_factor = round(fs / 8000); % Target roughly 8kHz sampling for plot
    if decimation_factor < 1
        decimation_factor = 1;
    end
    
    idxs = idx_min:decimation_factor:idx_max;
    
    v_plot = v(idxs);
    v_tilde_plot = v_tilde(idxs);
    t_plot = time_vec(idxs);
    
    % Store in struct as row vectors to ensure proper JSON array format for Plotly
    res.filename = wav_files(i).name;
    res.duration = duration;
    res.t = t_plot(:)';
    res.v = v_plot(:)';
    res.v_tilde = v_tilde_plot(:)';
    res.t_peak = time_vec(t_hat);
    res.v_peak = v(t_hat);
    res.t_l1 = time_vec(l1);
    res.v_l1 = v(l1);
    res.t_l2 = time_vec(l2);
    res.v_l2 = v(l2);
    
    results{i} = res;
    fprintf('Processed %s\n', res.filename);
end

% Create JSON manually since jsonencode might not be perfect in older MATLAB
% or just use jsonencode which is available in R2016b+
json_str = jsonencode(results);

% HTML Template
html = sprintf(['<!DOCTYPE html>\n' ...
'<html>\n' ...
'<head>\n' ...
'    <title>Interactive Diamant Time Domain Plot</title>\n' ...
'    <script src="https://cdn.plot.ly/plotly-2.24.1.min.js"></script>\n' ...
'    <style>\n' ...
'        body { font-family: Arial, sans-serif; background-color: #0f172a; color: #f8fafc; padding: 20px; }\n' ...
'        h1 { text-align: center; color: #38bdf8; }\n' ...
'        .chart-container { width: 100%%; max-width: 1200px; margin: 0 auto 30px auto; background: rgba(30,41,59,0.7); padding: 15px; border-radius: 10px; }\n' ...
'        .plot { width: 100%%; height: 400px; }\n' ...
'    </style>\n' ...
'</head>\n' ...
'<body>\n' ...
'    <h1>Interactive Time-Domain Duration (Diamant et al. 2019)</h1>\n' ...
'    <p style="text-align: center;">Results shown for a window of &plusmn;2 seconds around the dominant peak.</p>\n' ...
'    <div id="plots"></div>\n' ...
'\n' ...
'    <script>\n' ...
'        const data = %s;\n' ...
'        const container = document.getElementById("plots");\n' ...
'\n' ...
'        data.forEach((fileData, i) => {\n' ...
'            const div = document.createElement("div");\n' ...
'            div.className = "chart-container";\n' ...
'            const plotDiv = document.createElement("div");\n' ...
'            plotDiv.className = "plot";\n' ...
'            plotDiv.id = "plot" + i;\n' ...
'            div.appendChild(plotDiv);\n' ...
'            container.appendChild(div);\n' ...
'\n' ...
'            const trace_v = {\n' ...
'                x: fileData.t,\n' ...
'                y: fileData.v,\n' ...
'                type: "scatter",\n' ...
'                mode: "lines",\n' ...
'                name: "Signal",\n' ...
'                line: {color: "#38bdf8", width: 1.5}\n' ...
'            };\n' ...
'\n' ...
'            const trace_v_tilde = {\n' ...
'                x: fileData.t,\n' ...
'                y: fileData.v_tilde,\n' ...
'                type: "scatter",\n' ...
'                mode: "lines",\n' ...
'                name: "Envelope",\n' ...
'                line: {color: "#f43f5e", width: 2, dash: "dash"}\n' ...
'            };\n' ...
'\n' ...
'            const trace_markers = {\n' ...
'                x: [fileData.t_l2, fileData.t_peak, fileData.t_l1],\n' ...
'                y: [fileData.v_l2, fileData.v_peak, fileData.v_l1],\n' ...
'                type: "scatter",\n' ...
'                mode: "markers",\n' ...
'                name: "Edges & Peak",\n' ...
'                marker: {color: "#fbbf24", size: 10, symbol: ["x", "circle", "x"], line: {width: 2}}\n' ...
'            };\n' ...
'\n' ...
'            const layout = {\n' ...
'                title: {\n' ...
'                    text: `File: ${fileData.filename} | Duration: ${fileData.duration.toFixed(4)} s`,\n' ...
'                    font: {color: "#f8fafc"}\n' ...
'                },\n' ...
'                paper_bgcolor: "rgba(0,0,0,0)",\n' ...
'                plot_bgcolor: "rgba(0,0,0,0)",\n' ...
'                xaxis: { title: "Time (s)", gridcolor: "rgba(255,255,255,0.1)", color: "#94a3b8" },\n' ...
'                yaxis: { title: "Amplitude", gridcolor: "rgba(255,255,255,0.1)", color: "#94a3b8" },\n' ...
'                legend: { font: { color: "#f8fafc" } },\n' ...
'                hovermode: "closest"\n' ...
'            };\n' ...
'\n' ...
'            Plotly.newPlot(plotDiv.id, [trace_v, trace_v_tilde, trace_markers], layout, {responsive: true});\n' ...
'        });\n' ...
'    </script>\n' ...
'</body>\n' ...
'</html>'], json_str);

html_path = 'C:\Users\gorke\.gemini\antigravity-ide\brain\e1650f41-21c9-4f66-bd63-a6f32140d912\diamant_time_interactive.html';
fid = fopen(html_path, 'w');
fprintf(fid, '%s', html);
fclose(fid);

fprintf('Interactive HTML saved to %s\n', html_path);
